Bug fix for federation v2 controller manager can not start.
From v0.0.8 controller-manager does not support --install-crds=false parameter.
With this cmd args, we will get the following errors:
Error: unknown flag: --install-crds